
version: "3"

services:
  db:
    image: postgres:16-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata_game_server:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gamedb
      POSTGRES_PASSWORD: password
  game-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: game-server
    ports:
      - "8080:8080"
    volumes:
      - .:/game-server
    command: go run .
    restart: on-failure:2
    depends_on:
      - db

volumes:
  pgdata_game_server:
    name: pgdata_game_server
